apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  ports:
  - port: 8443
    targetPort: 8443
    nodePort: 80
  selector:
    name: argocd-server
  type: LoadBalancer
